name: Build

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        platform: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: "recursive"

      - name: Installing Linux Dependencies
        if: ${{ runner.os == 'Linux' }}
        run: |
          sudo apt update
          sudo apt install zlib1g-dev libcurl4-openssl-dev libssl-dev libunwind-dev pkg-config

      - name: Build crashpad
        run: |
          cmake -B cmake-build -D CRASHPAD_BUILD_TOOLS=On
          cmake --build cmake-build --parallel

      - name: Build crashpad with client-side stack traces
        run: |
          cmake -B cmake-build-stacks -D CRASHPAD_ENABLE_STACKTRACE=ON
          cmake --build cmake-build-stacks --parallel

      - name: Build crashpad Windows ARM64
        if: ${{ runner.os == 'Windows' }}
        run: |
          cmake -B cmake-build-arm64 -DCMAKE_TOOLCHAIN_FILE="cmake/toolchains/win_arm64.cmake" -DCRASHPAD_BUILD_TOOLS=On
          cmake --build cmake-build-arm64 --config RelWithDebInfo -- /p:Platform=ARM64

      - name: Build crashpad with client-side stack traces Windows ARM64
        if: ${{ runner.os == 'Windows' }}
        run: |
          cmake -B cmake-build-stacks-arm64 -DCMAKE_TOOLCHAIN_FILE="cmake/toolchains/win_arm64.cmake" -DCRASHPAD_ENABLE_STACKTRACE=ON
          cmake --build cmake-build-stacks-arm64 --config RelWithDebInfo -- /p:Platform=ARM64

  build-ios:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: "recursive"
      - run: |
          cmake -B crashpad-xcode -GXcode -DCMAKE_SYSTEM_NAME=iOS
          xcodebuild build -project crashpad-xcode/crashpad.xcodeproj

  build-mingw:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: "recursive"

      - uses: msys2/setup-msys2@v2
        with:
          msystem: clang64
          update: true
          install: >-
            git
            mingw-w64-clang-x86_64-cmake
            mingw-w64-clang-x86_64-ninja
            mingw-w64-clang-x86_64-hdf5
            mingw-w64-clang-x86_64-uasm
            mingw-w64-clang-x86_64-clang
            mingw-w64-clang-x86_64-lld
            tar
            xz

      - uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - shell: msys2 {0}
        run: |
          mkdir _build _deploy
          export MINGW_ROOT=/c/msys64
          cmake -GNinja -B_build -H. -DCMAKE_TOOLCHAIN_FILE=toolchains/msys2.cmake -DCMAKE_INSTALL_PREFIX=_deploy -D CRASHPAD_ENABLE_STACKTRACE=ON
          ninja -C _build -v install
          export name=crashpad-mingw64-`date +"%Y%m%d"`-${GITHUB_RUN_NUMBER}-${GITHUB_SHA}
          /usr/bin/tar cvfJ ${name}.tar.xz -C _deploy --transform "s,^./,${name}/," .

      - name: Upload artifacts to MinIO
        run: |
          python -m pip install awscli
          aws configure set aws_access_key_id crashpad
          aws configure set aws_secret_access_key $env:MINIO_SECRET_KEY
          aws configure set default.region us-east-1
          aws configure set default.s3.signature_version s3v4
          aws configure set s3.endpoint_url https://snapshots.workrave.org/
          aws s3 --endpoint-url https://snapshots.workrave.org/ cp (get-item crashpad-mingw64-*.tar.xz).Fullname s3://crashpad
        env:
           MINIO_SECRET_KEY: ${{ secrets.MINIO_SECRET_KEY }}
#(Get-ChildItem *entry.md | Select-Object -Expand FullName)