name: Build

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: Ubuntu (GCC 14.2.0)
            platform: ubuntu-24.04
            CC: gcc-14
            CXX: g++-14
          - name: Ubuntu (GCC 13.3.0)
            platform: ubuntu-24.04
            CC: gcc
            CXX: g++
          - name: Ubuntu (GCC 11.4.0)
            platform: ubuntu-22.04
            CC: gcc
            CXX: g++
          - name: Ubuntu (GCC 9.5.0)
            platform: ubuntu-22.04
            CC: gcc-9
            CXX: g++-9
          - name: Ubuntu (clang 18.1.3)
            platform: ubuntu-24.04
            CC: clang
            CXX: clang++
          - name: Ubuntu (clang 14.0.0)
            platform: ubuntu-22.04
            CC: clang
            CXX: clang++
          - name: Windows (x64)
            platform: windows-latest
          - name: Windows ClangCL (x64)
            platform: windows-latest
            CMAKE_DEFINES: -G 'Visual Studio 17 2022' -A x64 -T ClangCL
          - name: Windows (arm64)
            platform: windows-latest
            CMAKE_DEFINES: -DCMAKE_TOOLCHAIN_FILE=cmake/toolchains/win_arm64.cmake -A arm64
          - name: LLVM-MINGW (x64)
            platform: windows-latest
            MINGW: 1
            MINGW_PKG_PREFIX: x86_64-w64-mingw32
            MINGW_ASM_MASM_COMPILER: "'llvm-ml;-m64'"
            CMAKE_DEFINES: -DCRASHPAD_ZLIB_SYSTEM=OFF -DCRASHPAD_BUILD_TOOLS=OFF -G Ninja
          - name: LLVM-MINGW (arm64)
            platform: windows-latest
            MINGW: 1
            MINGW_PKG_PREFIX: aarch64-w64-mingw32
            CMAKE_DEFINES: -DCRASHPAD_ZLIB_SYSTEM=OFF -DCRASHPAD_BUILD_TOOLS=OFF -DCMAKE_TOOLCHAIN_FILE=cmake/toolchains/mingw_arm64.cmake -G Ninja
          - name: macOS
            platform: macos-latest
    name: ${{ matrix.name }}
    runs-on: ${{ matrix.platform }}
    env:
      CMAKE_DEFINES: "${{ matrix.CMAKE_DEFINES }}"
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: "recursive"

      - name: Installing Linux Dependencies
        if: ${{ runner.os == 'Linux' }}
        run: |
          sudo apt update
          sudo apt install clang zlib1g-dev libcurl4-openssl-dev libssl-dev libunwind-dev pkg-config

      - name: Installing LLVM-MINGW Dependencies
        if: ${{ runner.os == 'Windows' && matrix.MINGW == '1' }}
        shell: powershell
        env:
          MINGW_PKG_PREFIX: ${{ matrix.MINGW_PKG_PREFIX }}
          MINGW_ASM_MASM_COMPILER: ${{ matrix.MINGW_ASM_MASM_COMPILER }}
        run: . "cmake\scripts\install-llvm-mingw.ps1"

      - name: Build crashpad
        shell: bash
        run: |
          [ "${{ matrix.CC }}" ] && export CC="${{ matrix.CC }}"
          [ "${{ matrix.CXX }}" ] && export CXX="${{ matrix.CXX }}"
          echo "CMAKE_DEFINES=${CMAKE_DEFINES}"
          eval "cmake -B cmake-build -D CRASHPAD_BUILD_TOOLS=On $CMAKE_DEFINES"
          cmake --build cmake-build --parallel

      - name: Build crashpad with client-side stack traces
        shell: bash
        run: |
          [ "${{ matrix.CC }}" ] && export CC="${{ matrix.CC }}"
          [ "${{ matrix.CXX }}" ] && export CXX="${{ matrix.CXX }}"
          echo "CMAKE_DEFINES=${CMAKE_DEFINES}"
          eval "cmake -B cmake-build-stacks -D CRASHPAD_ENABLE_STACKTRACE=ON $CMAKE_DEFINES"
          cmake --build cmake-build-stacks --parallel

  build-ios:
    name: "iOS"
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: "recursive"
      - run: |
          cmake -B crashpad-xcode -GXcode -DCMAKE_SYSTEM_NAME=iOS
          xcodebuild build -project crashpad-xcode/crashpad.xcodeproj

  build-mingw:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: "recursive"

      - uses: msys2/setup-msys2@v2
        with:
          msystem: clang64
          update: true
          install: >-
            git
            mingw-w64-clang-x86_64-cmake
            mingw-w64-clang-x86_64-ninja
            mingw-w64-clang-x86_64-hdf5
            mingw-w64-clang-x86_64-uasm
            mingw-w64-clang-x86_64-clang
            mingw-w64-clang-x86_64-lld
            tar
            xz

      - uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - shell: msys2 {0}
        run: |
          mkdir _build _deploy
          export MINGW_ROOT=/c/msys64
          cmake -GNinja -B_build -H. -DCMAKE_TOOLCHAIN_FILE=cmake/toolchains/msys2.cmake -DCMAKE_INSTALL_PREFIX=_deploy -D CRASHPAD_ENABLE_STACKTRACE=ON
          ninja -C _build -v install
          export name=crashpad-mingw64-`date +"%Y%m%d"`-${GITHUB_RUN_NUMBER}-${GITHUB_SHA}
          /usr/bin/tar cvfJ ${name}.tar.xz -C _deploy --transform "s,^./,${name}/," .

      - name: Upload artifacts to MinIO
        run: |
          python -m pip install awscli
          aws configure set aws_access_key_id crashpad
          aws configure set aws_secret_access_key $env:MINIO_SECRET_KEY
          aws configure set default.region us-east-1
          aws configure set default.s3.signature_version s3v4
          aws configure set s3.endpoint_url https://snapshots.workrave.org/
          aws s3 --endpoint-url https://snapshots.workrave.org/ cp (get-item crashpad-mingw64-*.tar.xz).Fullname s3://crashpad
        env:
          MINIO_SECRET_KEY: ${{ secrets.MINIO_SECRET_KEY }}
#(Get-ChildItem *entry.md | Select-Object -Expand FullName)
